### ISSUE TITLE
Have experience with GitHub & Git

### ISSUE THREAD

**Issue by prakashupes** [prakashupes/GSoC-pgRouting#1]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/pgrouting
- [x] checkout to the master branch of `upstream`
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] put link of branch on pgRouting gitter chat
- [x] put link of issue on pgRouting gitter chat

**Comment by prakashupes** [comment]
### Create remote named upstream
Command:
git remote add upstream https://github.com/pgRouting/pgrouting
git remote -v


`
origin	https://github.com/prakashupes/GSoC-pgRouting.git (fetch)
origin	https://github.com/prakashupes/GSoC-pgRouting.git (push)
upstream	https://github.com/pgRouting/pgrouting (fetch)
upstream	https://github.com/pgRouting/pgrouting (push)
`

**Comment by prakashupes** [comment]
### checkout to the master branch of upstream

git fetch upstream 
git checkout upstream/master
git branch -a
```

* (HEAD detached at upstream/master)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/boost-alg
  remotes/origin/develop
  remotes/origin/master
  remotes/origin/moore-alg
  remotes/origin/revert-9-toposort
  remotes/upstream/develop
  remotes/upstream/gh-pages
  remotes/upstream/master
  remotes/upstream/release/2.5
  remotes/upstream/release/2.6
```

**Comment by prakashupes** [comment]
### create new branch with name gsoc-test
git branch gsoc-testgit
git checkout gsoc-test
```
Switched to branch 'gsoc-test'
```
git status
```
On branch gsoc-test
nothing to commit, working tree clean

**Comment by prakashupes** [comment]
### push the newly created branch
```
git push origin gsoc-test

```

**Comment by cvvergara** [comment]
Pass
