### ISSUE TITLE
Build locally pgRouting

### ISSUE THREAD

**Issue by prakashupes** [prakashupes/GSoC-pgRouting#2]
- [x] Install requirements
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] build locally pgRouting
- [x] put link of issue on pgRouting gitter chat

**Comment by prakashupes** [comment]
I have built, install and tested pgRouting. Here links are provided for the works

**Comment by prakashupes** [comment]
1.[make cmake work](https://github.com/prakashupes/pgrouting/issues/2)
2.[compile and install locally ](https://github.com/prakashupes/pgrouting/issues/3)
3.[generate the queries of the documentation](https://github.com/prakashupes/pgrouting/issues/4)
4.[generate documentation](https://github.com/prakashupes/pgrouting/issues/7)
5.[test](https://github.com/prakashupes/pgrouting/issues/6)

**Comment by cvvergara** [comment]
Passed
